# Generated by Django 5.0 on 2023-12-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('refrigerated', models.BooleanField(verbose_name='Refrigerado')),
                ('restricted', models.BooleanField(verbose_name='Restringido')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='producto', max_length=20, verbose_name='Nombre')),
                ('qty', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('cost', models.IntegerField(default=0, verbose_name='Costo')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='inv_manager.category', verbose_name='Categoría')),
                ('storage_place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='inv_manager.storage', verbose_name='Lugar de almacenado')),
            ],
        ),
    ]
